# EnderchestSlots config.

permission.slots:
  4: # Le nombre ici correspond au nombre de slot accordé au joueur
    permission: "slots.enderchest.4"
    default: user

item:
  id: "minecraft:barrier"
  name: '§o§cBloqué'